files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/pic32mz_ef_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: 2B41A7C0958709485E7B304B5F61D617
  logicalPath: config/pic32mz_ef_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2B41A7C0958709485E7B304B5F61D617
- generatedChecksum: 3F734BF05F77A6A15923D26C72B16BB5
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3F734BF05F77A6A15923D26C72B16BB5
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 2DABAED8044A2293937DBD7764727C6D
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2DABAED8044A2293937DBD7764727C6D
- generatedChecksum: 1F19DD53C12B0F7628B7A8AA1C18050F
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1F19DD53C12B0F7628B7A8AA1C18050F
- generatedChecksum: E060BD7028EF5A479136A2F93ACD1B68
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: E060BD7028EF5A479136A2F93ACD1B68
- generatedChecksum: 8952B56585611F5BC2481C97EA04AB3A
  logicalPath: config/pic32mz_ef_sk/peripheral/tmr1
  name: plib_tmr1.c
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8952B56585611F5BC2481C97EA04AB3A
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mz_ef_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: D6CA782ABE1EA0BA4F7ADEA9CF3B0CC8
  logicalPath: config/pic32mz_ef_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: D6CA782ABE1EA0BA4F7ADEA9CF3B0CC8
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_ef_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 3C465EE2268CD765C11300F75C6560CC
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C465EE2268CD765C11300F75C6560CC
- generatedChecksum: 2E3278A543811A4080BCD8883D91F6F8
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 2E3278A543811A4080BCD8883D91F6F8
- generatedChecksum: 32D7539D9231F3C159ABECE91A0281EA
  logicalPath: config/pic32mz_ef_sk/peripheral/tmr1
  name: plib_tmr1.h
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 32D7539D9231F3C159ABECE91A0281EA
- generatedChecksum: 69E7C8CDAB1B32838331EE261170CEA4
  logicalPath: config/pic32mz_ef_sk/peripheral/tmr1
  name: plib_tmr1_common.h
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 69E7C8CDAB1B32838331EE261170CEA4
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config/pic32mz_ef_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: C734E3299D476FDDB140E61BA3B5C31B
  logicalPath: config/pic32mz_ef_sk
  name: p32MZ2048EFH144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C734E3299D476FDDB140E61BA3B5C31B
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
