format_version: v1.0
type: UniqueComponent
attributes: {id: tmr2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TIMER_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '100000000'}
  - type: Long
    attributes: {id: TIMER_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '29999'}
  - type: Boolean
    attributes: {id: TMR_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: 'true'}
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '30', y: '120', id: tmr2}
