format_version: v1.0
type: UniqueComponent
attributes: {id: spi3}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SPIS_SLAVE_SELECT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi3, value: 'true'}
  - type: Integer
    attributes: {id: SPI_BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi3, value: '49'}
  - type: Boolean
    attributes: {id: SPI_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '340', y: '20', id: spi3}
